#!/bin/bash

set -e

cd `dirname $0`

npm run typecheck
npm run lint

SSH_HOST="root@misc5.tkeith.com"

ssh "$SSH_HOST" "docker stop aloria || true"

rsync -a --delete --exclude node_modules --exclude .git --exclude .next --exclude .env --exclude hardhat ./ "$SSH_HOST":/root/aloria

ssh "$SSH_HOST" "cd /root/aloria && cp prod.env .env && /root/.local/share/pnpm/pnpm dlx codapt@latest run"

# tell the user deploy is done, press enter to ssh into the server and see the docker logs
echo "Deploy complete. Press Enter to SSH into the server and see the docker logs."

read -n 1 -s -r -p "Press Enter to SSH into the server and see the docker logs..."

ssh "$SSH_HOST" "docker logs -f aloria"
